# Generated by Django 5.1.1 on 2026-09-10 21:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceSegment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('excel_import', 'Importación Excel (Campus)'), ('manual', 'Selección manual'), ('dynamic', 'Regla dinámica')], default='excel_import', max_length=20)),
                ('filter_rules', models.JSONField(blank=True, default=dict, help_text="Solo aplica cuando source_type='dynamic'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre interno')),
                ('meta_template_name', models.CharField(max_length=150, unique=True, verbose_name='Nombre en Meta Business Manager')),
                ('language', models.CharField(default='es_CO', max_length=10)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utilidad'), ('authentication', 'Autenticación')], default='utility', max_length=20)),
                ('body_text', models.TextField(help_text='Usa {{1}}, {{2}}, etc. para parámetros dinámicos.')),
                ('header_type', models.CharField(choices=[('none', 'Sin encabezado'), ('image', 'Imagen'), ('video', 'Video'), ('document', 'Documento (PDF)')], default='none', max_length=10)),
                ('header_media_url', models.URLField(blank=True)),
                ('buttons', models.JSONField(blank=True, default=list, help_text='Lista de botones URL, ej. [{"text": "Ver más", "url": "https://..."}]')),
                ('status', models.CharField(choices=[('draft', 'Borrador local'), ('pending', 'Pendiente de aprobación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('channel', models.CharField(default='whatsapp', editable=False, max_length=20)),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('scheduled', 'Programada'), ('sending', 'Enviando'), ('sent', 'Enviada'), ('paused', 'Pausada'), ('cancelled', 'Cancelada'), ('failed', 'Fallida')], default='draft', max_length=15)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, help_text='Límite de envíos por minuto (Rate Limiting Meta API).')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='communications.audiencesegment')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='communications.messagetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=180, verbose_name='Nombre completo')),
                ('document_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Número de documento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(db_index=True, help_text='Formato E.164, ej. +573001234567', max_length=20, verbose_name='Teléfono (WhatsApp)')),
                ('academic_program', models.CharField(blank=True, max_length=150, verbose_name='Programa académico')),
                ('semester', models.CharField(blank=True, max_length=10, verbose_name='Semestre')),
                ('role', models.CharField(choices=[('aspirante', 'Aspirante'), ('estudiante', 'Estudiante'), ('egresado', 'Egresado'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('whatsapp_opt_in', models.CharField(choices=[('suscrito', 'Suscrito'), ('no_contactado', 'No contactado'), ('baja', 'Dado de baja')], default='no_contactado', max_length=20)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, help_text='ej. excel_campus, formulario_web, importacion_manual', max_length=50, verbose_name='Origen del registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='communicati_phone_fcbd91_idx'), models.Index(fields=['document_number'], name='communicati_documen_e2447f_idx')],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone_snapshot', models.CharField(max_length=20)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En cola'), ('sent', 'Enviado'), ('delivered', 'Entregado'), ('read', 'Leído'), ('failed', 'Fallido'), ('opted_out', 'Excluido (baja)')], default='pending', max_length=15)),
                ('provider', models.CharField(blank=True, help_text='twilio | meta | mock', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='communications.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='communications.contact')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('message_sent', 'Mensaje enviado'), ('message_delivered', 'Mensaje entregado'), ('message_read', 'Mensaje leído'), ('message_failed', 'Mensaje fallido'), ('message_replied', 'Respuesta recibida'), ('opted_out', 'Se dio de baja'), ('segment_added', 'Agregado a audiencia'), ('note', 'Nota interna')], max_length=30)),
                ('channel', models.CharField(default='whatsapp', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('broadcast_recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='communications.broadcastrecipient')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='communications.campaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='communications.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SegmentMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.contact')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.audiencesegment')),
            ],
        ),
        migrations.AddField(
            model_name='audiencesegment',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='segments', through='communications.SegmentMembership', to='communications.contact'),
        ),
        migrations.AddIndex(
            model_name='broadcastrecipient',
            index=models.Index(fields=['campaign', 'status'], name='communicati_campaig_1bebfa_idx'),
        ),
        migrations.AddConstraint(
            model_name='broadcastrecipient',
            constraint=models.UniqueConstraint(fields=('campaign', 'contact'), name='unique_campaign_contact'),
        ),
        migrations.AddIndex(
            model_name='contactevent',
            index=models.Index(fields=['contact', '-created_at'], name='communicati_contact_c223fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='segmentmembership',
            constraint=models.UniqueConstraint(fields=('segment', 'contact'), name='unique_segment_contact'),
        ),
    ]
