# Generated by Django 5.1.1 on 2026-09-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ("communications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppWebhookEvent",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_key", models.CharField(max_length=300, unique=True)),
                ("provider_message_id", models.CharField(db_index=True, max_length=150)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("inbound", "Mensaje entrante"), ("status", "Estado de mensaje")],
                        max_length=20,
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=30)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
