# Generated by Django 5.1.1 on 2026-09-27 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiencesegment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='broadcastrecipient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='campaign',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='contactevent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='broadcastrecipient',
            name='unique_campaign_contact',
        ),
        migrations.RemoveConstraint(
            model_name='segmentmembership',
            name='unique_segment_contact',
        ),
        migrations.RemoveIndex(
            model_name='broadcastrecipient',
            name='communicati_campaig_1bebfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='communicati_phone_fcbd91_idx',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='communicati_documen_e2447f_idx',
        ),
        migrations.RemoveIndex(
            model_name='contactevent',
            name='communicati_contact_c223fe_idx',
        ),
        migrations.RenameField(
            model_name='contactevent',
            old_name='payload',
            new_name='metadata',
        ),
        migrations.RenameField(
            model_name='segmentmembership',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='audiencesegment',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='audiencesegment',
            name='filter_rules',
        ),
        migrations.RemoveField(
            model_name='audiencesegment',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='broadcastrecipient',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='broadcastrecipient',
            name='params',
        ),
        migrations.RemoveField(
            model_name='broadcastrecipient',
            name='queued_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='default_params',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='rate_limit_per_minute',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='sent_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contactevent',
            name='broadcast_recipient',
        ),
        migrations.RemoveField(
            model_name='contactevent',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='body_text',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='buttons',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='header_media_url',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='header_type',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='language',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='campaign',
            name='delivered_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='param_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='audiencesegment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audiencesegment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='audiencesegment',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='audiencesegment',
            name='source_type',
            field=models.CharField(choices=[('excel_import', 'Importación Excel'), ('manual', 'Manual'), ('filter', 'Filtro Dinámico')], default='excel_import', max_length=50),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.contact'),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='phone_snapshot',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='provider',
            field=models.CharField(default='meta', max_length=50),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='channel',
            field=models.CharField(default='whatsapp', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.audiencesegment'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SCHEDULED', 'Programada'), ('SENDING', 'Enviando'), ('SENT', 'Enviada'), ('FAILED', 'Fallida')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.messagetemplate'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='academic_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='document_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='semester',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.CharField(default='excel_campus', max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contactevent',
            name='channel',
            field=models.CharField(default='whatsapp', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactevent',
            name='event_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='category',
            field=models.CharField(default='UTILITY', max_length=50),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='meta_template_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='status',
            field=models.CharField(default='APPROVED', max_length=50),
        ),
        migrations.AlterField(
            model_name='segmentmembership',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_memberships', to='communications.contact'),
        ),
        migrations.AlterField(
            model_name='segmentmembership',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='segmentmembership',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communications.audiencesegment'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentmembership',
            unique_together={('segment', 'contact')},
        ),
    ]
