# Generated by Django 5.1.1 on 2026-09-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_whatsappwebhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappwebhookevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
