# Generated by Django 5.1.1 on 2026-09-30 04:17
#
# NOTA: esta migracion depende a proposito de 0004 (no de 0001).
# `variable_types` nacio en una rama distinta a la de
# `0004_whatsappwebhookevent_payload`. Al mergear, 0004 quedo como migracion de
# merge dependiendo de esta, pero en las bases donde 0004 ya estaba aplicada
# Django abortaba con InconsistentMigrationHistory (y la columna nunca se
# creaba). Invirtiendo la dependencia, `migrate` la aplica sola en cualquier
# base sin importar su estado previo. No renombrar: las bases que ya la
# aplicaron quedarian con una migracion desconocida.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_whatsappwebhookevent_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='variable_types',
            field=models.JSONField(blank=True, default=dict, help_text='Tipos de variables, ej. {"1": "text", "2": "date"}'),
        ),
    ]
