# Generated by Django 5.1.1 on 2026-09-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='variable_types',
            field=models.JSONField(blank=True, default=dict, help_text='Tipos de variables, ej. {"1": "text", "2": "date"}'),
        ),
    ]
