# Generated by Django 5.1.1 on 2026-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_messagetemplate_variable_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppWebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=300, unique=True)),
                ('provider_message_id', models.CharField(db_index=True, max_length=150)),
                ('event_type', models.CharField(choices=[('inbound', 'Mensaje entrante'), ('status', 'Estado de mensaje')], max_length=20)),
                ('status', models.CharField(blank=True, max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Fragmento crudo del evento de Meta, para conservar el motivo de un failed.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='broadcastrecipient',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
