# Generated by Django 5.1.1 on 2026-09-19

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('knowledge', '0002_category_intent_remove_producto_categoria_faq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('ended', 'Finalizada'), ('pending', 'Pendiente de asesor')], default='active', max_length=20)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('escalation_reason', models.TextField(blank=True)),
                ('advisor_question', models.TextField(blank=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Conversación del chatbot',
                'verbose_name_plural': 'Conversaciones del chatbot',
                'ordering': ['-created_at'],
            },
        ),
    ]