# Generated by Django 5.1.1 on 2026-09-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_chatconversation_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='linked_ticket_number',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
