"""
Django settings for PuntoTdeA project.

Generated by 'django-admin startproject' using Django 5.1.1.
"""

import os
from pathlib import Path
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent


def _env_flag(name: str, default: str = "false") -> bool:
    return os.environ.get(name, default).lower() in {"1", "true", "yes"}


DEBUG = _env_flag("DJANGO_DEBUG", "true")

# En produccion el SECRET_KEY es obligatorio: el valor de desarrollo solo
# sirve para que `python manage.py ...` funcione sin configurar nada.
_DEV_SECRET_KEY = "django-insecure-hx28lhdhlu55l9ui6*pieyql=ck2*z(ooa(0tjsv9+qm7#ts-7"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured(
            "DJANGO_SECRET_KEY es obligatorio cuando DJANGO_DEBUG=false. "
            "Genera uno con: python -c \"import secrets; print(secrets.token_urlsafe(64))\""
        )
    SECRET_KEY = _DEV_SECRET_KEY

# Render publica RENDER_EXTERNAL_HOSTNAME (p. ej. "puntotdea.onrender.com"). Lo
# usamos como fallback para no depender de copiar el dominio a mano en el panel.
_RENDER_HOST = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS",
        ",".join(
            host
            for host in ("localhost", "127.0.0.1", "testserver", _RENDER_HOST)
            if host
        ),
    ).split(",")
    if host.strip()
]
if DEBUG and "*" not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append("*")

# El túnel de Cloudflare se conserva para desarrollo; en Render el origen real
# es el dominio de onrender.com.
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "DJANGO_CSRF_TRUSTED_ORIGINS",
        ",".join(
            origin
            for origin in (
                f"https://{_RENDER_HOST}" if _RENDER_HOST else "",
            )
            if origin
        ),
    ).split(",")
    if origin.strip()
]

INSTALLED_APPS = [
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "channels",
    # Aplicaciones del proyecto PuntoTdeA
    "dashboard",
    "cases",
    "knowledge",
    "communications",
    "announcements",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # whitenoise sirve los estaticos de collectstatic; debe ir tras
    # SecurityMiddleware y antes de cualquier middleware que pueda responder.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "PuntoTdeA.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "PuntoTdeA.wsgi.application"
ASGI_APPLICATION = "PuntoTdeA.asgi.application"


# Database: PostgreSQL when DB_HOST or DATABASE_URL is set, otherwise SQLite
#
# Render entrega la conexion como DATABASE_URL; docker compose y el CI usan las
# variables DB_* sueltas. SePrioriza DATABASE_URL si estan presentes.
if os.environ.get("DATABASE_URL"):
    _db = urlparse(os.environ["DATABASE_URL"])
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (_db.path or "/").lstrip("/") or "django_db",
            "USER": _db.username or "django_user",
            "PASSWORD": _db.password or "",
            "HOST": _db.hostname or "",
            "PORT": str(_db.port or 5432),
            "CONN_MAX_AGE": 600,
        }
    }
elif os.environ.get("DB_HOST"):
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "django_db"),
            "USER": os.environ.get("DB_USER", "django_user"),
            "PASSWORD": os.environ.get("DB_PASSWORD", "django_password"),
            "HOST": os.environ["DB_HOST"],
            "PORT": os.environ.get("DB_PORT", "5432"),
            "CONN_MAX_AGE": 600,
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


REDIS_URL = os.environ.get("REDIS_URL", "")
if REDIS_URL:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [REDIS_URL]},
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer",
        }
    }


REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Punto TdeA API",
    "DESCRIPTION": "Documentación de las APIs del sistema Punto TdeA (casos, comunicaciones, base de conocimiento y avisos).",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/",
    "ENUM_NAME_OVERRIDES": {
        "ConversationStatusEnum": "cases.models.Conversation.Status",
        "MessageTemplateStatusEnum": "communications.models.MessageTemplate.Status",
        "CampaignStatusEnum": "communications.models.Campaign.Status",
        "BroadcastRecipientStatusEnum": "communications.models.BroadcastRecipient.Status",
        "KnowledgeArticleStatusEnum": "knowledge.models.KnowledgeArticle.STATUS_CHOICES",
        "ChatConversationStatusEnum": "knowledge.models.ChatConversation.STATUS_CHOICES",
    },
}


_cors_origins = os.environ.get("WIDGET_ALLOWED_ORIGINS", "http://localhost:8000,http://127.0.0.1:8000")
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(",") if o.strip()]
CORS_ALLOW_CREDENTIALS = True


META_VERIFY_TOKEN = os.environ.get("META_VERIFY_TOKEN", "")
META_APP_ID = os.environ.get("META_APP_ID", "")
META_APP_SECRET = os.environ.get("META_APP_SECRET", "")
META_ACCESS_TOKEN = os.environ.get("META_ACCESS_TOKEN", "")
WHATSAPP_PHONE_NUMBER_ID = os.environ.get("WHATSAPP_PHONE_NUMBER_ID", "")
WHATSAPP_API_VERSION = os.environ.get("WHATSAPP_API_VERSION", "v21.0")
META_GRAPH_API_URL = os.environ.get("META_GRAPH_API_URL", "https://graph.facebook.com")
META_REQUEST_TIMEOUT = float(os.environ.get("META_REQUEST_TIMEOUT", "10"))

# Meta Marketing API (anuncios en WhatsApp Status / "Ads in Status").
# El token de sistema de WhatsApp NO sirve para anuncios: hace falta un token
# de usuario con el permiso `ads_management`.
META_ADS_ACCESS_TOKEN = os.environ.get("META_ADS_ACCESS_TOKEN", "")
META_AD_ACCOUNT_ID = os.environ.get("META_AD_ACCOUNT_ID", "")
META_FB_PAGE_ID = os.environ.get("META_FB_PAGE_ID", "")
META_WHATSAPP_PHONE = os.environ.get("META_WHATSAPP_PHONE", "")
META_BUSINESS_ID = os.environ.get("META_BUSINESS_ID", "")

ALLOW_WEBHOOK_SIMULATOR = os.environ.get(
    "ALLOW_WEBHOOK_SIMULATOR",
    "true" if DEBUG else "false",
).lower() in {"1", "true", "yes"}

# Token compartido con el BFF para la API interna (/campanas/api/).
# La UI de campanas entra con la sesion del navegador; este token cubre a los
# consumidores de servicio (BFF) cuando DEBUG=False.
INTERNAL_API_TOKEN = os.environ.get("INTERNAL_API_TOKEN", "")

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/login/"


AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

LANGUAGE_CODE = "es-co"
TIME_ZONE = "America/Bogota"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# whitenoise con manifiesto: los archivos se comprimen (gzip/brotli) y se
# versionan por hash, asi que un CSS viejo nunca se sirve tras un despliegue.
if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Sin MEDIA_ROOT escribible (p. ej. el contenedor de Render sin disco), Django
# lanza OSError al subir un archivo. Se desactiva la subida en vez de 500.
MEDIA_UPLOADS_ENABLED = os.environ.get("MEDIA_UPLOADS_ENABLED", "true").lower() in {
    "1",
    "true",
    "yes",
}

FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ImageField models exist; silence check when Pillow is not installed in local/CI.
SILENCED_SYSTEM_CHECKS = ["fields.E210"]

# --- Ajustes de produccion (Render termina el TLS delante de la app) ---
if not DEBUG:
    # Render enruta por su proxy e inyecta el protocolo original en esta cabecera.
    # Sin esto Django creeria que la peticion es http:// y rejectaria el CSRF
    # de los formularios enviados por https://.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = _env_flag("DJANGO_SECURE_SSL_REDIRECT", "true")
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS", "0"))
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "SAMEORIGIN"
    # El proxy de Render no expone el IP real del cliente en REMOTE_ADDR.
    USE_X_FORWARDED_HOST = True

KNOWLEDGE_SETTINGS = {
    'MIN_CONFIDENCE': 0.7,
    'MAX_RESULTS': 5,
    'DEFAULT_EMBEDDING_DIMENSION': 512,
}
