# Generated by Django 5.1.1 on 2026-10-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusAd',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('campaign_id', models.CharField(blank=True, max_length=40)),
                ('ad_set_id', models.CharField(blank=True, max_length=40)),
                ('creative_id', models.CharField(blank=True, max_length=40)),
                ('ad_id', models.CharField(blank=True, max_length=40)),
                ('audience_ids', models.JSONField(blank=True, default=list)),
                ('daily_budget', models.BigIntegerField(default=2000000)),
                ('countries', models.JSONField(blank=True, default=list)),
                ('advantage_audience', models.BooleanField(default=False)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('paused', 'Pausado'), ('active', 'Activo'), ('error', 'Error')], default='draft', max_length=10)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_ads', to='announcements.announcement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
