# Generated by Django 5.1.1 on 2026-10-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_statusad'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusad',
            name='segment_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
